const stocks = [
  {symbol:'2330',name:'台積電',market:'TW',sector:'半導體',price:1085,change:1.88,score:86,signal:'偏多',logo:'台',dims:[92,84,75,88],pe:'22.8x',growth:'+31.4%',roe:'29.2%',margin:'57.8%',vol:'24.1%',thesis:['AI 與高效能運算需求支撐先進製程成長。','毛利率與資本效率維持同業領先。','估值高於長期中位數，但獲利成長提供部分支撐。'],risk:'先進製程資本支出龐大；地緣政治與半導體景氣循環可能造成波動。'},
  {symbol:'2454',name:'聯發科',market:'TW',sector:'IC 設計',price:1380,change:-0.72,score:78,signal:'觀察',logo:'發',dims:[83,70,72,82],pe:'19.5x',growth:'+18.2%',roe:'24.6%',margin:'49.1%',vol:'27.5%',thesis:['旗艦手機晶片市占與產品組合改善。','邊緣 AI 與車用平台帶來中期選擇權。','短線動能降溫，適合等待更佳風險報酬。'],risk:'智慧手機需求復甦速度、客戶集中及同業價格競爭。'},
  {symbol:'2881',name:'富邦金',market:'TW',sector:'金融',price:91.4,change:0.44,score:73,signal:'中性',logo:'富',dims:[76,68,79,67],pe:'11.2x',growth:'+12.1%',roe:'12.7%',margin:'—',vol:'18.2%',thesis:['壽險與銀行雙引擎提供獲利支撐。','股利能力與資本水準逐步改善。','利率與匯率仍是季度損益主要變數。'],risk:'避險成本、債券評價與監理資本制度變化。'},
  {symbol:'AAPL',name:'Apple',market:'US',sector:'消費電子',price:218.27,change:0.83,score:76,signal:'觀察',logo:'A',dims:[88,67,59,82],pe:'31.7x',growth:'+6.5%',roe:'157%',margin:'46.2%',vol:'22.3%',thesis:['服務營收與生態系黏性支撐高品質現金流。','裝置端 AI 有機會推動換機循環。','高估值需要更強的成長重新加速。'],risk:'中國市場競爭、監管壓力與硬體換機週期不確定。'},
  {symbol:'NVDA',name:'NVIDIA',market:'US',sector:'半導體',price:142.63,change:2.41,score:89,signal:'偏多',logo:'N',dims:[96,91,61,84],pe:'36.4x',growth:'+69.0%',roe:'91.8%',margin:'74.5%',vol:'42.6%',thesis:['AI 加速運算需求與軟體生態形成強大護城河。','資料中心成長與新品週期仍具能見度。','估值隱含高預期，任何成長放緩都可能放大波動。'],risk:'客戶自研晶片、出口限制、供應鏈集中與高估值回撤。'},
  {symbol:'MSFT',name:'Microsoft',market:'US',sector:'軟體服務',price:478.04,change:-0.31,score:84,signal:'偏多',logo:'M',dims:[93,79,68,89],pe:'34.2x',growth:'+15.3%',roe:'35.1%',margin:'69.8%',vol:'20.4%',thesis:['Azure 與企業軟體訂閱提供穩健複利。','Copilot 商業化可提升單客價值。','AI 基礎建設投入短期壓抑自由現金流轉換。'],risk:'雲端競爭、AI 資本支出回報與反壟斷監管。'}
];
const indices={TW:[['加權指數','23,214.72',.62],['櫃買指數','252.18',-.21],['台指期近月','23,196',.55],['美元／台幣','32.41',-.12]],US:[['S&P 500','6,012.28',.41],['NASDAQ','19,546.27',.78],['Dow Jones','42,408.91',-.16],['VIX','14.82',-2.11]]};
let current=stocks[0],market='TW',watch=JSON.parse(localStorage.getItem('wangyue-watch')||'[]'),activeRecGroup='circle';
const selectedRecGroups=new Set(['circle']);
const recGroupNames={circle:'長下引線',group2:'由綠轉紅',group3:'過三線'};
const recGroupRules={circle:'下影線 ≥ K 棒實體 2 倍',group2:'MACD 柱狀體由綠轉紅',group3:'收盤價同時高於 MA5、MA10、MA20'};
const recGroupSettings=JSON.parse(localStorage.getItem('wangyue-rec-groups')||'{"circle":{"market":"all","risk":"balanced","horizon":"long"},"group2":{"market":"TW","risk":"balanced","horizon":"medium"},"group3":{"market":"US","risk":"conservative","horizon":"long"}}');
const technicalSignals={
  '2330':{shadow:true,macd:true,mas:true},'2454':{shadow:true,macd:true,mas:true},'2881':{shadow:true,macd:false,mas:true},
  'AAPL':{shadow:false,macd:true,mas:true},'NVDA':{shadow:true,macd:true,mas:true},'MSFT':{shadow:true,macd:false,mas:true}
};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function money(s){return s.market==='TW'?`NT$ ${s.price.toLocaleString()}`:`US$ ${s.price.toLocaleString()}`}
async function updateLiveQuotes(){const status=$('#quoteStatus');if(location.protocol==='file:'){status.textContent='行情狀態 · GitHub 上傳後啟用';status.classList.remove('live');return}status.textContent='行情狀態 · 更新中…';try{const onGitHub=location.hostname.endsWith('github.io');const quoteUrl=onGitHub?`./data/quotes.json?t=${Date.now()}`:'/api/quotes';const response=await fetch(quoteUrl,{cache:'no-store'});if(!response.ok)throw new Error('quote service unavailable');const payload=await response.json();if(!payload.quotes?.length)throw new Error('quotes not ready');payload.quotes.forEach(q=>{const stock=stocks.find(s=>s.symbol===q.symbol);if(stock&&Number.isFinite(q.price)){stock.price=q.price;stock.change=q.change}});const updated=new Date(payload.updatedAt);status.textContent=`${onGitHub?'GitHub 延遲行情':'即時／延遲'} · ${updated.toLocaleString('zh-TW',{timeZone:'Asia/Taipei',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}`;status.classList.add('live');renderRows();renderAnalysis();renderWatch();renderRecommendations()}catch(error){status.textContent='行情尚未更新 · 點擊重試';status.classList.remove('live')}}
function renderIndices(){ $('#marketStrip').innerHTML=indices[market].map(x=>`<div class="index-card"><div><span>${x[0]}</span><b>${x[1]}</b></div><em class="${x[2]>=0?'up':'down'}">${x[2]>=0?'+':''}${x[2]}%</em></div>`).join('') }
function renderSignals(){const d=market==='TW'?[['趨勢結構','多頭排列','指數站上季線'],['市場廣度','62%','上漲家數占比'],['估值水位','略高','本益比高於五年均值']]:[['趨勢結構','偏多','大型股維持強勢'],['市場廣度','58%','成分股站上月線'],['風險情緒','穩定','VIX 位於低檔']];$('#signals').innerHTML=d.map(x=>`<div class="signal"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join('');$('#temperature').textContent=market==='TW'?68:64}
function renderFocus(){const s=market==='TW'?stocks[0]:stocks[4];$('#focusCard').innerHTML=`<div class="focus-main"><div class="ticker-logo">${s.logo}</div><div><h3>${s.name}</h3><p>${s.symbol} · ${s.sector}</p></div><div class="focus-score"><b>${s.score}</b><span>綜合評分</span></div></div><div class="focus-copy">${s.thesis[0]} ${s.thesis[1]}</div><div class="mini-tags"><span class="tag">基本面強</span><span class="tag warn">留意估值</span></div>`;current=s}
function renderRows(filter='all'){const data=filter==='all'?stocks:stocks.filter(s=>s.market===filter);$('#stockRows').innerHTML=data.map(s=>`<tr><td><strong>${s.name}</strong><small>${s.symbol} · ${s.sector}</small></td><td>${s.market==='TW'?'台灣':'美國'}</td><td>${money(s)}</td><td class="${s.change>=0?'up':'down'}">${s.change>=0?'+':''}${s.change}%</td><td><div class="score-bar"><b>${s.score}</b><i style="--score:${s.score}%"></i></div></td><td><span class="signal-pill">${s.signal}</span></td><td><button class="row-action" data-symbol="${s.symbol}">→</button></td></tr>`).join('');$$('.row-action').forEach(b=>b.onclick=()=>openStock(b.dataset.symbol))}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));const names={overview:['MARKET PULSE','市場總覽'],analysis:['STOCK RESEARCH','個股分析'],recommend:['SMART SCREENER','智能選股'],watchlist:['YOUR COLLECTION','觀察清單'],strategy:['METHODOLOGY','策略說明']};$('#pageEyebrow').textContent=names[id][0];$('#pageTitle').textContent=names[id][1];window.scrollTo({top:0,behavior:'smooth'});if(id==='watchlist')renderWatch();if(id==='recommend')renderRecommendations()}
function openStock(symbol){current=stocks.find(s=>s.symbol===symbol)||current;renderAnalysis();showView('analysis')}
function renderAnalysis(){const s=current;$('#tickerLogo').textContent=s.logo;$('#stockMeta').textContent=`${s.market==='TW'?'台灣':'美國'} · ${s.sector}`;$('#stockName').innerHTML=`${s.name} <small>${s.symbol}</small>`;$('#stockPrice').textContent=money(s);$('#stockChange').textContent=`${s.change>=0?'+':''}${s.change}%`;$('#stockChange').className=s.change>=0?'up':'down';$('#mainScore').textContent=s.score;$('.score-ring').style.setProperty('--ring',`${s.score*3.6}deg`);$('#scoreLabel').textContent=s.score>=85?'研究優先級：高':s.score>=75?'研究優先級：中高':'研究優先級：中';const labels=['基本面','趨勢動能','估值合理性','風險品質'],colors=['#258365','#4ca985','#c59a52','#618c78'];$('#dimensionBars').innerHTML=s.dims.map((v,i)=>`<div class="dimension"><div class="dimension-top"><span>${labels[i]}</span><b>${v}</b></div><div class="dimension-track"><span style="--width:${v}%;--color:${colors[i]}"></span></div></div>`).join('');$('#thesisList').innerHTML=s.thesis.map(x=>`<li>${x}</li>`).join('');$('#riskText').textContent=s.risk;const metrics=[['預估本益比',s.pe,'估值'],['營收成長',s.growth,'年增率'],['股東權益報酬率',s.roe,'ROE'],['毛利率',s.margin,'獲利品質'],['年化波動度',s.vol,'風險']];$('#metricGrid').innerHTML=metrics.map(x=>`<div class="metric panel"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join('');const p=s.price;$('#scenarioGrid').innerHTML=[['保守情境',p*.82,'-18%','需求或估值下修'],['基準情境',p*1.1,'+10%','獲利依預期發展'],['樂觀情境',p*1.27,'+27%','成長與估值同步上修']].map((x,i)=>`<div class="scenario ${i===1?'base':''}"><span>${x[0]}</span><b>${s.market==='TW'?'NT$':'US$'} ${x[1].toFixed(s.market==='TW'?0:2)}</b><small class="${i?'up':'down'}">${x[2]} · ${x[3]}</small></div>`).join('');$('#watchButton').textContent=watch.includes(s.symbol)?'✓ 已在觀察清單':'＋ 加入觀察'}
function toggleWatch(){const i=watch.indexOf(current.symbol);if(i>=0)watch.splice(i,1);else watch.push(current.symbol);localStorage.setItem('wangyue-watch',JSON.stringify(watch));renderAnalysis();toast(i>=0?'已移出觀察清單':'已加入觀察清單')}
function renderWatch(){const data=stocks.filter(s=>watch.includes(s.symbol));$('#watchCards').innerHTML=data.length?data.map(s=>`<div class="watch-card" data-symbol="${s.symbol}"><b>${s.name} · ${s.symbol}</b><span>${money(s)}　評分 ${s.score}</span></div>`).join(''):'<p class="muted">目前還沒有股票</p>';$$('.watch-card').forEach(c=>c.onclick=()=>openStock(c.dataset.symbol))}
function recommendationWeights(risk,horizon){let w={fund:35,trend:25,value:25,risk:15};if(risk==='conservative')w={fund:32,trend:13,value:20,risk:35};if(risk==='aggressive')w={fund:36,trend:38,value:16,risk:10};if(horizon==='long'){w.fund+=8;w.trend-=5;w.value+=2;w.risk-=5}if(horizon==='short'){w.fund-=12;w.trend+=18;w.value-=6}const total=w.fund+w.trend+w.value+w.risk;return[w.fund,w.trend,w.value,w.risk].map(x=>x/total)}
function saveRecommendationGroup(){recGroupSettings[activeRecGroup]={market:$('#recMarket').value,risk:$('#recRisk').value,horizon:$('#recHorizon').value};localStorage.setItem('wangyue-rec-groups',JSON.stringify(recGroupSettings))}
function selectRecommendationGroup(group){if(selectedRecGroups.has(group)){if(selectedRecGroups.size===1){toast('請至少保留一個選股條件');return}selectedRecGroups.delete(group)}else selectedRecGroups.add(group);activeRecGroup=group;$$('.condition-group').forEach(b=>{const on=selectedRecGroups.has(b.dataset.group);b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});const groups=[...selectedRecGroups];$('#circleIndicators').innerHTML=groups.map((g,i)=>`<div><i>${i+1}</i><span><b>${recGroupNames[g]}</b><small>${recGroupRules[g]}</small></span></div>`).join('');$('#groupDescription').innerHTML=`<b>已選：${groups.map(g=>recGroupNames[g]).join('＋')}</b><span>須符合全部 ${groups.length} 項訊號</span>`;renderRecommendations()}
function renderRecommendations(){const marketChoice=$('#recMarket').value,risk=$('#recRisk').value,horizon=$('#recHorizon').value,weights=recommendationWeights(risk,horizon);const signalKeys={circle:'shadow',group2:'macd',group3:'mas'},groups=[...selectedRecGroups];let candidates=stocks.filter(s=>(marketChoice==='all'||s.market===marketChoice)&&groups.every(g=>technicalSignals[s.symbol][signalKeys[g]]));const pool=candidates.map(s=>({...s,match:Math.round(s.dims.reduce((sum,v,i)=>sum+v*weights[i],0))})).sort((a,b)=>b.match-a.match).slice(0,3);const riskNames={balanced:'穩健平衡',conservative:'保守防禦',aggressive:'積極成長'},horizonNames={long:'長期',medium:'中期',short:'短期'},groupLabel=groups.map(g=>recGroupNames[g]).join('＋');$('#recommendProfile').textContent=`${groupLabel} · ${riskNames[risk]} · ${horizonNames[horizon]}`;if(!pool.length){$('#recommendCards').innerHTML=`<article class="panel"><b>目前沒有股票同時符合「${groupLabel}」</b><p class="muted" style="margin:8px 0 0">可減少勾選條件、切換市場，或等待下一個交易日重新掃描。</p></article>`;return}$('#recommendCards').innerHTML=pool.map((s,i)=>`<article class="panel recommend-card" data-symbol="${s.symbol}"><div class="recommend-rank">0${i+1}</div><div class="recommend-main"><h3>${s.name} <small>${s.symbol} · ${s.market==='TW'?'台股':'美股'}</small></h3><p>${groups.map(g=>recGroupRules[g]).join('；')}。</p><div class="recommend-tags">${groups.map(g=>`<span class="tag tech-pass">✓ ${recGroupNames[g]}</span>`).join('')}</div></div><div class="recommend-score"><b>${groups.length}/${groups.length}</b><span>訊號通過</span></div></article>`).join('');$$('.recommend-card').forEach(c=>c.onclick=()=>openStock(c.dataset.symbol))}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
$$('.nav-item').forEach(n=>n.onclick=()=>showView(n.dataset.view));$$('.condition-group').forEach(b=>b.onclick=()=>selectRecommendationGroup(b.dataset.group));$$('.segmented button').forEach(b=>b.onclick=()=>{$$('.segmented button').forEach(x=>x.classList.remove('active'));b.classList.add('active');market=b.dataset.market;renderIndices();renderSignals();renderFocus()});$$('.filters button').forEach(b=>b.onclick=()=>{$$('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderRows(b.dataset.filter)});$('#goAnalysis').onclick=()=>openStock(current.symbol);$('#watchButton').onclick=toggleWatch;$('#browseButton').onclick=()=>showView('overview');$('#openRecommender').onclick=()=>showView('recommend');$('#quoteStatus').onclick=updateLiveQuotes;$('#generateRecommendations').onclick=()=>{saveRecommendationGroup();renderRecommendations();toast('推薦名單已更新')};$('#searchInput').oninput=e=>{const q=e.target.value.trim().toLowerCase();const data=q?stocks.filter(s=>(s.symbol+s.name+s.sector).toLowerCase().includes(q)):[];$('#searchResults').innerHTML=data.map(s=>`<div class="search-result" data-symbol="${s.symbol}"><b>${s.name}</b>　${s.symbol} · ${s.market==='TW'?'台股':'美股'}</div>`).join('');$('#searchResults').classList.toggle('show',!!data.length);$$('.search-result').forEach(r=>r.onclick=()=>{$('#searchInput').value='';$('#searchResults').classList.remove('show');openStock(r.dataset.symbol)})};
renderIndices();renderSignals();renderFocus();renderRows();renderAnalysis();renderRecommendations();updateLiveQuotes();setInterval(updateLiveQuotes,60000);
